#!/bin/bash

set -eu

if [ $# -ne 3 ] ; then
    echo "Clone IMAGE to HOSTNAME with IPADDRESS."
    echo "  Usage: $0 IMAGE HOSTNAME IPADDRESS"
    exit 1
fi

IMAGE="$1"
HNAME="$2"
IPADDR="$3"

MDIR="/var/lib/machines/"
DOMAIN="$(hostname -d)"
NEWNAME="${HNAME}.${DOMAIN}"

echo "Prepare '${HNAME}' with IP-address '${IPADDR}' from image '${IMAGE}'."

[ -d "$MDIR" ] || mkdir -pv  "$MDIR"

## clone/fetch image:
if [[ "$IMAGE" = https://* ]] ; then
    machinectl --verify=checksum pull-tar "$IMAGE" "$HNAME"
else
    machinectl clone "$IMAGE" "$HNAME"
fi

## find the legacy IP-address of the template:
OLDIP="$(grep -m1 -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' \
         "${MDIR}/${HNAME}/etc/bigbluebutton/nginx/sip.nginx")"

echo "Replace IP-address '${OLDIP}' by '${IPADDR}'."
grep -Ilr "${OLDIP}" "${MDIR}/${HNAME}" | grep -v /var/log/ | \
    xargs sed -i "s/${OLDIP}/${IPADDR}/g"

OLDNAME="$(grep -m1 server_name "${MDIR}/${HNAME}/etc/nginx/sites-available/bigbluebutton" | \
              sed -e "s/^\W*server_name\W*//" -e "s/;\W*$//")"

echo "Replace hostname '${OLDNAME}' by '${NEWNAME}'."
grep -Ilr "${OLDNAME}" "${MDIR}/${HNAME}" | grep -v /var/log/ | \
    xargs sed -i "s/${OLDNAME}/${NEWNAME}/g"

# rename cert directory
mv -v "${MDIR}/${HNAME}/etc/letsencrypt/live/$OLDNAME/" "${MDIR}/${HNAME}/etc/letsencrypt/live/$NEWNAME/"

# remove hostkeys:
rm -v ${MDIR}/${HNAME}/etc/ssh/ssh_host_*

##
# systemd-run -M ${HNAME} /usr/bin/bbb-conf --setip ${HNAME}.lehrerfortbildung-bw.de
# systemd-run -M ${HNAME} /usr/bin/bbb-conf --clean



echo "Done.  Run the container with 'machinectl start ${HNAME}'."
