
- name: Install containerhost for LFB BBB
  hosts: containerhost
  remote_user: root
  become: no
  vars_files: vault
  vars:
    extra_pkgs:
      - ufw
      - bc
      - systemd-container
      - debootstrap
      - bridge-utils
      - tmux
      - fail2ban

    guest_network: "{{ vault_guest_network }}"
    static_auth_secret: "{{ vault_static_auth_secret }}"
    container_image: "{{ vault_container_image }}"
    monhost_ip: "{{ vault_monhost_ip }}"

    ## list of debian containers to set up:
    turnserver: "turn{{ inventory_hostname | replace('b3srv', '')}}"
    debcontainer:
      - "{{ turnserver.split('.')[0] }}"

  tasks:
    - import_role:
        name: up2date-debian
    - import_role:
        name: security
      tags:
        - on_install
    - import_role:
        name: prepare-containerhost
      tags:
        - on_install
    - import_role:
        name: debcontainer
    - import_role:
        name: bbbcontainer
    - import_role:
        name: monitoring
      tags:
        - on_install
        - monitoring
    - import_role:
        name: munin-node
      tags:
        - on_install
