- name: Monitoring of the containers by script from containerhost
  hosts: bigbluebutton
  remote_user: root
  become: no
  gather_facts: no

  roles:
    - disable-checkmk
    - monitoring-scripts 

- name: Monitoring of the containerhosts
  hosts: containerhost
  remote_user: root
  become: no
  gather_facts: no
  vars_files: vault

  vars:
    monhost_ip: "{{ vault_monhost_ip }}"

  roles:
    - monitoring
