- name: Install scalelite for LFB BBB
  hosts: all
  remote_user: root
  become: no
  vars_files: vault
  vars:
    scalelite_localnet: "{{ vault_scalelite_localnet }}"
    scalelite_pg_password: "{{ vault_scalelite_pg_password }}"
    scalelite_dockernet: "{{ vault_scalelite_dockernet }}"

  vars_prompt:
    - name: "letsencryptemail"
      prompt:
        In case you would like to fetch a LetsEncrypt certificate and have
        not done so yet, provide your eMail address here.  Leave empty to
        just continue
      private: no

  roles:
    - up2date-ubuntu
    - scalelite
