---

- hosts: all
  remote_user: root
  become: no
  vars_files: vault

  vars:
    keystodeploy: "{{ vault_keystodeploy }}"
 
  tasks:
  - name: Deploy SSH-Keys to remote host
    authorized_key:
      user: root
      key: "{{ keystodeploy|map(attribute='sshkey')|join('\n') }}"
      exclusive: true
