- name: Install packages
  apt:
    name:
      - munin-node
    state: latest

- name: Provide munin plugin script
  copy:
    src: munin-bbb
    dest: /usr/local/bin/munin-bbb
    mode: "0755"

- name: Run plugin as root to allow access to data
  copy:
    src: "munin-bbb.conf"
    dest: "/etc/munin/plugin-conf.d/munin-bbb.conf"
  notify: Restart munin-node

- name: Activate plugins
  file:
    src: /usr/local/bin/munin-bbb
    dest: /etc/munin/plugins/{{ item }}
    state: link
  loop:
    - bbb-numAttendees
    - bbb-numListeners
    - bbb-numMeetings
    - bbb-numWithVideo
    - bbb-numWithVoice
  notify: Restart munin-node

- name: Find unnecessary plugins
  find:
    paths: /etc/munin/plugins/
    file_type: link
    patterns:
      - "if_err_vb-bbb*"
      - "if_err_virbr0"
      - "if_err_enp*"
      - "if_vb-bbb*"
      - "if_enp*"
      - "irqstats"
  register: result
  notify: Restart munin-node

- name: Remove unnecessary plugins
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ result.files }}"
  notify: Restart munin-node

- name: Allow access from monitoring host
  lineinfile:
    path: /etc/munin/munin-node.conf
    line: "allow ^{{ monhost_ip | replace('.','\\.') }}$"
    insertafter: "^allow ^::1$$"
  notify: Restart munin-node

- name: Open port in ufw
  ufw:
    rule: allow
    port: '4949'
    proto: tcp
