- name: Install packages
  apt:
    name:
      - munin-node
      - bc
    state: latest

- name: Provide munin plugin script
  copy:
    src: munin-bbb
    dest: /usr/local/bin/munin-bbb
    mode: "0755"

- name: Make sure bbb-stats dir exists
  file:
    path: /var/log/bbb-stats/
    state: directory

- name: Provide access to data through hard links
  file:
    src: "/var/lib/machines/{{ item }}/var/cache/checkbbb/overview"
    dest: "/var/log/bbb-stats/{{ item }}"
    state: hard
  loop: "{{ bbbcontainer }}"

- name: Activate plugins
  file:
    src: /usr/local/bin/munin-bbb
    dest: /etc/munin/plugins/{{ item }}
    state: link
  loop:
    - bbb-numAttendees
    - bbb-numListeners
    - bbb-numMeetings
    - bbb-numWithVideo
    - bbb-numWithVoice
  notify: Restart munin-node

- name: Find unnecessary plugins
  find:
    paths: /etc/munin/plugins/
    file_type: link
    patterns:
      - "if_err_vb-bbb*"
      - "if_err_virbr0"
      - "if_err_enp*"
      - "if_vb-bbb*"
      - "if_enp*"
      - "irqstats"
  register: result

- name: Remove unnecessary plugins
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ result.files }}"
  notify: Restart munin-node

- name: Allow access from monitoring host
  lineinfile:
    path: /etc/munin/munin-node.conf
    line: "allow ^{{ monhost_ip | replace('.','\\.') }}$"
    insertafter: "^allow ^::1$$"
  notify: Restart munin-node

- name: Open port in ufw
  ufw:
    rule: allow
    port: '4949'
    proto: tcp
