- name: Add postgres user
  become: true
  become_user: postgres
  postgresql_user:
    db: postgres
    name: scalelite
    password: "{{ scalelite_pg_password }}"
    role_attr_flags: SUPERUSER

- name: Grant access from network {{ scalelite_localnet }}
  postgresql_pg_hba:
    dest: /etc/postgresql/10/main/pg_hba.conf
    contype: host
    # restrict to user and db scalelite?
    users: all
    databases: all
    source: "{{ scalelite_localnet }}"
    method: md5

- name: Grant access from network {{ scalelite_dockernet }}
  postgresql_pg_hba:
    dest: /etc/postgresql/10/main/pg_hba.conf
    contype: host
    # restrict to user and db scalelite?
    users: all
    databases: all
    source: "{{ scalelite_dockernet }}"
    method: md5

- name: Create DB scalelite on target
  become: true
  become_user: postgres
  postgresql_db:
    name: scalelite
    owner: scalelite






