#!/bin/bash
#
# Call this script as bbb-X, where X is one of:
#   numMeetings|numAttendees|numWithVoice|numWithVideo|numListeners
#
#
#

CFG="$1"
set -eu

BHOST="$(echo $(hostname) | sed 's/b3srv//')"
MDIR="/var/lib/machines/"
DATA="/var/cache/checkbbb/overview"
BBBNUM="$(find $MDIR -maxdepth 1 -name "bbb???-???" | wc -l)"

if [ "$(basename $0)" = "munin-bbb" ] ; then
    METRIC="numAttendees"
else
    METRIC="$(echo $(basename $0) | sed 's/bbb-//')"
fi

case $CFG in
    config)
        cat <<EOF
graph_title BBB Meeting Data: $METRIC
graph_category bbb
graph_info BBB Meeting Numbers: $METRIC
graph_args -l 0
EOF
        echo -n "graph_order "
        for i in $(seq 1 ${BBBNUM}) ; do
            N=$(printf "%03d" $i)
            echo -n "${METRIC}-bbb$BHOST-${N} "
        done
        echo "${METRIC}-bbb$BHOST-SUM"
        echo "${METRIC}-bbb$BHOST-001.label bbb${BHOST}-001"
        echo "${METRIC}-bbb$BHOST-001.draw AREA"
        for i in $(seq 2 ${BBBNUM}) ; do
            N=$(printf "%03d" $i)
            echo "${METRIC}-bbb$BHOST-${N}.label bbb${BHOST}-${N}"
            echo "${METRIC}-bbb$BHOST-${N}.draw STACK"
        done
        echo "${METRIC}-bbb$BHOST-SUM.label bbb${BHOST}-SUM"
        echo "${METRIC}-bbb$BHOST-SUM.draw LINE"
        exit 0
        ;;
esac

S=0
STR=""
for i in $(seq 1 ${BBBNUM}) ; do
    N=$(printf "%03d" $i)
    V=$((grep -o "${METRIC}=[0-9]\+" "${MDIR}/bbb${BHOST}-${N}/${DATA}" 2>/dev/null \
            || true ) | sed -e "s%${METRIC}=%%")
    STR="${STR}${METRIC}-bbb$BHOST-${N}.value ${V}\n"
    [ -n "$V" ] && S=$(( ${S} + ${V} ))
done
echo -e "${STR}${METRIC}-bbb$BHOST-SUM.value ${S}"
