- name: Wait for meetings to end on the server
  pause:
    minutes: 120

- name: Start containers
  systemd:
    name: systemd-nspawn@{{ item }}.service
    state: started
  register: startcont
  loop: "{{ bbbcontainer }}"

- name: Wait for containers to settle
  pause:
    seconds: 10
  when: startcont.changed

- name: Purge packages causing troubles within the container
  apt:
    name:
      - resolvconf
      - makedev
    purge: true
    state: absent
  delegate_to: "{{ item }}.{{ ansible_domain }}"
  loop: "{{ bbbcontainer }}"

## Packages needed for bbb-install.sh to succeed; python3-requests for monitoring
- name: Add necessary packages to ubuntu container
  apt:
    name:
      - wget
      - ca-certificates
      - bind9-host
      - python3-requests
    state: latest
  delegate_to: "{{ item }}.{{ ansible_domain }}"
  loop: "{{ bbbcontainer }}"

## Provide certificates
- name: Make sure /local/certs/ exists
  file:
    path: "/local/certs/"
    state: directory
    mode: '0755'
  delegate_to: "{{ item }}.{{ ansible_domain }}"
  loop: "{{ bbbcontainer }}"

- name: Deploy certificate, privkey
  copy:
    src: privkey.pem
    dest: "/local/certs/"
    owner: root
    group: root
    mode: "0600"
  delegate_to: "{{ item }}.{{ ansible_domain }}"
  loop: "{{ bbbcontainer }}"

- name: Deploy certificate, fullchain
  copy:
    src: fullchain.pem
    dest: "/local/certs/"
    owner: root
    group: root
    mode: "0644"
  delegate_to: "{{ item }}.{{ ansible_domain }}"
  loop: "{{ bbbcontainer }}"

- name: Run bbb-install.sh
  shell: >
    wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh |
    sed -r "s|(deb +(\[.+\] +)*)https://|\1http://HTTPS///|" |
    bash -s -- -v xenial-22 -d -s {{ item }}.{{ ansible_domain }}
    > /root/bbb-install.log
  delegate_to: "{{ item }}.{{ ansible_domain }}"
  loop: "{{ bbbcontainer }}"
  tags:
    - bbb_install_sh

- name: Fix apt sources for proxy use
  shell: >
    for FILE in $(find /var/lib/machines/bbb???-???/etc/apt/ -name "*.list") ;
    do sed -i "s|https://|http://HTTPS///|w /tmp/sed.log" $FILE ;
    [ -s /tmp/sed.log ] && echo "'https' replaced in '$FILE'." || true ; done
  register: result
  changed_when: '"replaced" in result.stdout'

- name: Update apt package cache on container and run full-upgrade
  apt:
    update-cache: yes
    upgrade: full
    autoremove: yes
    autoclean: yes
  delegate_to: "{{ item }}.{{ ansible_domain }}"
  loop: "{{ bbbcontainer }}"

- name: Mask dev-hugepages.mount
  systemd:
    name: dev-hugepages.mount
    masked: yes
  delegate_to: "{{ item }}.{{ ansible_domain }}"
  loop: "{{ bbbcontainer }}"

- name: Mask disable-transparent-huge-pages.service
  systemd:
    name: disable-transparent-huge-pages.service
    masked: yes
  delegate_to: "{{ item }}.{{ ansible_domain }}"
  loop: "{{ bbbcontainer }}"

- name: Set the shared secret
  command: /usr/bin/bbb-conf --setsecret {{ sharedsecret }}
  delegate_to: "{{ item }}.{{ ansible_domain }}"
  loop: "{{ bbbcontainer }}"
  when: not template.stat.exists

## Copy script for monitoring with checkmk to containers
- name: Copy check-script to container BBB
  copy:
    src: checkbbb_for_chost.py
    dest: /usr/local/bin/checkbbb_for_chost.py
    owner: root
    group: root
    mode: 0755
  delegate_to: "{{ item }}.{{ ansible_domain }}"
  loop: "{{ bbbcontainer }}"

- name: Stop BBB containers from containerhost
  systemd:
    name: systemd-nspawn@{{ item }}.service
    state: stopped
  loop: "{{ bbbcontainer }}"
