- name: Wait for meetings to end on the server
  pause:
    minutes: 120

- name: Run bbb-install.sh
  shell: >-
    wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh |
    sed -r "s|(deb +(\[.+\] +)*)https://|\1http://HTTPS///|" |
    bash -s -- -v xenial-22 -s {{ item }}.{{ ansible_domain }}
  delegate_to: "{{ item }}.{{ ansible_domain }}"
  loop: "{{ bbbcontainer }}"

- name: Fix apt sources for proxy use
  shell: >-
    for FILE in $(find /etc/apt/ -name "*.list") ;
    do sed -i "s|https://|http://HTTPS///|" $FILE ; done
  delegate_to: "{{ item }}.{{ ansible_domain }}"
  loop: "{{ bbbcontainer }}"

- name: Update apt package cache on container and run full-upgrade
  apt:
    update-cache: yes
    upgrade: full
    autoremove: yes
    autoclean: yes
  delegate_to: "{{ item }}.{{ ansible_domain }}"
  loop: "{{ bbbcontainer }}"

- name: Wait a minute for containers to settle
  pause:
    minutes: 1

- name: Stop BBB containers from containerhost
  systemd:
    name: systemd-nspawn@{{ item }}.service
    state: stopped
  loop: "{{ bbbcontainer }}"
