- name: Copy check-script to container BBB
  copy:
    src: checkbbb_for_chost.py
    dest: /var/lib/machines/{{ item  }}/usr/local/bin/checkbbb_for_chost.py
    owner: root
    group: root
    mode: 0755
  loop: "{{ bbbcontainer }}"

- name: Make sure output does not exists (creation moved to check script)
  file:
    path: /var/lib/machines/{{ item }}/var/cache/checkbbb
    state: absent
  loop: "{{ bbbcontainer }}"


