- name: install packages
  apt:
    name:
      - certbot
      - coturn
      - acl
    state: latest

- name: fetch LE certificate
  command:
    cmd: >
      certbot certonly
      --standalone
      --noninteractive
      --agree-tos
      --preferred-challenges http
      --email {{ letsencryptemail }}
      --deploy-hook 'systemctl restart coturn'
      -d {{ inventory_hostname }}
    creates: /etc/letsencrypt/live/
  when: letsencryptemail is defined and letsencryptemail | length > 0

- name: allow turnserver access to LE directories
  acl:
    path: "{{ item }}"
    entity: turnserver
    etype: user
    permissions: x
    state: present
  with_items:
    - /etc/letsencrypt/live/
    - /etc/letsencrypt/archive/
  notify: "restart coturn"

- name: find all private keys
  find:
    paths: "/etc/letsencrypt/archive/{{ inventory_hostname }}"
    patterns: privkey*.pem
  register: privkeys

- name: allow turnserver access to LE private key
  acl:
    path: "{{ item.path }}"
    entity: turnserver
    etype: user
    permissions: r
    state: present
  loop: "{{ privkeys.files }}"
  notify: "restart coturn"

- name: Set default ACL for LE directory to r (needed for new keys)
  acl:
    path: "/etc/letsencrypt/archive/{{ inventory_hostname }}"
    entity: turnserver
    etype: user
    permissions: r
    default: yes
    state: present

- name: prepare for service/timer overrides
  file:
    path: "/etc/systemd/system/{{ item }}"
    state: directory
  loop:
    - coturn.service.d
    - certbot.timer.d

- name: allow coturn to access lower ports
  copy:
    src: coturn-override.conf
    dest: /etc/systemd/system/coturn.service.d/override.conf
  notify: "restart coturn"

- name: run certbot timer only during the night
  copy:
    src: certbot-override.conf
    dest: /etc/systemd/system/certbot.timer.d/override.conf
  notify: "reload systemd"

- name: adapt turnserver.conf
  blockinfile:
    path: /etc/turnserver.conf
    block: |
      listening-port=3478
      tls-listening-port=443
      fingerprint
      lt-cred-mech
      static-auth-secret={{ static_auth_secret }}
      realm={{ ansible_domain }}
      cert=/etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem
      pkey=/etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem
      dh2066
      no-tlsv1
      no-tlsv1_1
  notify: "restart coturn"
